spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/users?currentSchema=spring
    driver-class-name: org.postgresql.Driver
server:
  port: 83
error:
  include-message: ALWAYS
  include-stacktrace: NEVER