spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://db:5432/classifier_service
    driver-class-name: org.postgresql.Driver
server:
  port: 81