spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/poster?currentSchema=spring
    driver-class-name: org.postgresql.Driver
server:
  port: 81
error:
  include-message: ALWAYS
  include-stacktrace: NEVER