FROM openjdk:11-jdk-slim
MAINTAINER ITAacademyAfisha

COPY target/Classifier-service-1.0.0-SNAPSHOT.jar Classifier-service-1.0.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/Classifier-service-1.0.0-SNAPSHOT.jar"]