CREATE DATABASE users WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'Russian_Russia.1251';

ALTER DATABASE users OWNER TO postgres;

\connect users

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA spring;


ALTER SCHEMA spring OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE spring.authorities (
    id bigint NOT NULL,
    role_name text
);


ALTER TABLE spring.authorities OWNER TO postgres;

ALTER TABLE spring.authorities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spring.authorities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE spring.users (
    uuid uuid NOT NULL,
    dt_create timestamp(3) without time zone,
    dt_update timestamp(3) without time zone,
    mail character varying(50) NOT NULL,
    nick character varying(30) NOT NULL,
    status character varying(20),
    password text NOT NULL
);


ALTER TABLE spring.users OWNER TO postgres;


CREATE TABLE spring.users_authorities (
    users_uuid uuid NOT NULL,
    authorities_id bigint NOT NULL
);


ALTER TABLE spring.users_authorities OWNER TO postgres;


ALTER TABLE ONLY spring.authorities
    ADD CONSTRAINT authorities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY spring.users
    ADD CONSTRAINT unique_mail_key UNIQUE (mail);

ALTER TABLE ONLY spring.users_authorities
    ADD CONSTRAINT users_authorities_pkey PRIMARY KEY (users_uuid, authorities_id);



ALTER TABLE ONLY spring.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (uuid);


ALTER TABLE ONLY spring.users_authorities
    ADD CONSTRAINT authority_id_fk FOREIGN KEY (authorities_id) REFERENCES spring.authorities(id);


ALTER TABLE ONLY spring.users_authorities
    ADD CONSTRAINT user_uuid_fk FOREIGN KEY (users_uuid) REFERENCES spring.users(uuid);

